authors:
  jaywhj:
    name: Aaron Wang
    avatar: https://avatars.githubusercontent.com/jaywhj
    url: https://jaywhj.netlify.app/
    email: junewhj@qq.com
    description: Minimalism
  squidfunk:
    name: Martin Donath
    avatar: https://avatars.githubusercontent.com/u/932156
    url: https://github.com/squidfunk
    email: xxx@gmail.com
    description: MkDocs Material

