authors:
  jaywhj:
    name: Aaron Wang
    description: Minimalism
    avatar: https://avatars.githubusercontent.com/jaywhj
    url: https://jaywhj.netlify.app/
  squidfunk:
    name: Martin Donath
    description: MkDocs Material
    avatar: https://avatars.githubusercontent.com/u/932156
    url: https://github.com/squidfunk

